name: Deployment

on:
  push:
    branches: [ "release" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build osu-sharp/osu-sharp.csproj --configuration Release

      - name: Pack
        run: dotnet pack osu-sharp/osu-sharp.csproj --configuration Release --no-build

      - name: Publish Package
        run: dotnet nuget push osu-sharp/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
